### ISSUE TITLE
Make color configurable

### ISSUE THREAD

**Issue by zenangst** [zenangst/ChangeMarks#2]

**Comment by zenangst** [comment]
Fixed by https://github.com/zenangst/ChangeMarks/pull/3

**Comment by revolter** [comment]
@zenangst, for some reason, the color is not saved for me.

**Comment by zenangst** [comment]
@revolter I'll have a look, does it never change or is it when you relaunch Xcode?

**Comment by zenangst** [comment]
@revolter try installing 2.0.3 and see if that works better for you.

**Comment by revolter** [comment]
@zenangst, I change it, even press <kbd>Enter</kbd> in every input field, and after closing the popup, nothing is changed, and if I go back, it shows the default colour.

**Comment by zenangst** [comment]
@revolter Weird, it works here :scream: 
You are using Xcode 6.x?

**Comment by revolter** [comment]
@zenangst, `Version 6.3.2 (6D2105)`

**Comment by zenangst** [comment]
@revolter is this still an issue?

**Comment by revolter** [comment]
@zenangst, No, it works instantly and after a restart too in Xcode `Version 7.2 (7C68)`

**Comment by zenangst** [comment]
@revolter thanks for following up, I'll close this :)
