### ISSUE TITLE
xCode 6.4 - doesn't work (or I can't understand how it works

### ISSUE THREAD

**Issue by gerchicov-bp** [zenangst/ChangeMarks#23]

**Comment by revolter** [comment]
Same here

**Comment by revolter** [comment]
@gerchicov-bp check out [this branch](https://github.com/revolter/ChangeMarks/tree/patch-1) where I added Xcode 6 compatibility

**Comment by zenangst** [comment]
I'm just gonna close this, totally missed it when it was first posted.
